// AUTO-GENERATED by scripts/generate-seat-views.mjs — do not edit by hand.
// Drop a panorama named after its seat (e.g. public/renders/main/G22.jpg)
// and re-run `npm run gen:seat-views` (runs automatically on dev/build).

export const generatedSeatViews: Record<string, Record<string, string>> = {
  "main": {
    "A22": "/renders/main/A22.jpg"
  }
};
