import type { Auditorium } from '@/types';

/**
 * Real seat totals per hall, derived from the per-row seat counts the seat maps
 * actually render:
 *   - Le Phénix (main)        → components/SeatMap/SeatMap.tsx  (buildMain)
 *   - Salle de l'Âme (chamber) → components/SeatMap2/SeatMap2.tsx (buildLayout)
 *
 * The landing page can't import those (they're client components), so the row
 * counts are mirrored here. If you change a row in either seat map, update the
 * matching array below so the marketing numbers stay truthful.
 */

const sum = (arr: readonly number[]) => arr.reduce((a, b) => a + b, 0);

/* ── Le Phénix (main) — fixed 18-seat centre block on every row + L/R sides ── */
const MAIN_CENTRE_BLOCK = 18;
const MAIN_ROWS = 18; // 10 front + 8 back
const MAIN_LEFT_FRONT = [13, 12, 13, 13, 13, 14, 14, 15, 15, 16];
const MAIN_RIGHT_FRONT = [12, 13, 13, 13, 14, 14, 15, 15, 16, 16];
const MAIN_LEFT_BACK = [16, 16, 16, 15, 15, 14, 13, 12];
const MAIN_RIGHT_BACK = [16, 16, 16, 15, 15, 14, 13, 12];

/* ── Salle de l'Âme (chamber) — left + centre + right block per row ── */
const CHAMBER_LEFT_FRONT = [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8];
const CHAMBER_CENTRE_FRONT = [7, 8, 8, 8, 9, 9, 9, 9, 10, 10, 11];
const CHAMBER_RIGHT_FRONT = [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7];
const CHAMBER_LEFT_BACK = [8, 8, 8, 8, 8, 8, 8, 8, 8];
const CHAMBER_CENTRE_BACK = [11, 11, 12, 11, 12, 12, 13, 13, 13];
const CHAMBER_RIGHT_BACK = [7, 7, 7, 7, 7, 7, 7, 7, 7];

/** Exact seat totals as generated by the seat maps. */
export const SEAT_TOTALS: Record<Auditorium, number> = {
  main:
    MAIN_CENTRE_BLOCK * MAIN_ROWS +
    sum(MAIN_LEFT_FRONT) +
    sum(MAIN_RIGHT_FRONT) +
    sum(MAIN_LEFT_BACK) +
    sum(MAIN_RIGHT_BACK),
  chamber:
    sum(CHAMBER_LEFT_FRONT) +
    sum(CHAMBER_CENTRE_FRONT) +
    sum(CHAMBER_RIGHT_FRONT) +
    sum(CHAMBER_LEFT_BACK) +
    sum(CHAMBER_CENTRE_BACK) +
    sum(CHAMBER_RIGHT_BACK),
};

export const roundToNearest10 = (n: number) => Math.round(n / 10) * 10;

/** Seat totals rounded to the nearest 10, for display on the landing page. */
export const SEAT_TOTALS_ROUNDED: Record<Auditorium, number> = {
  main: roundToNearest10(SEAT_TOTALS.main),
  chamber: roundToNearest10(SEAT_TOTALS.chamber),
};
