// AUTO-GENERATED by scripts/generate-seat-views.mjs — do not edit by hand.
// Drop a panorama named after its seat (e.g. public/renders/main/G22.jpg)
// and re-run `npm run gen:seat-views` (runs automatically on dev/build).

export const generatedSeatViews: Record<string, Record<string, string>> = {
  "chamber": {
    "A12": "/renders/chamber/A12.webp",
    "A19": "/renders/chamber/A19.webp",
    "A4": "/renders/chamber/A4.webp",
    "K14": "/renders/chamber/K14.webp",
    "K23": "/renders/chamber/K23.webp",
    "K4": "/renders/chamber/K4.webp",
    "L14": "/renders/chamber/L14.webp",
    "L23": "/renders/chamber/L23.webp",
    "L4": "/renders/chamber/L4.webp",
    "T15": "/renders/chamber/T15.webp",
    "T25": "/renders/chamber/T25.webp",
    "T4": "/renders/chamber/T4.webp"
  },
  "main": {
    "A22": "/renders/main/A22.webp",
    "A38": "/renders/main/A38.webp",
    "A7": "/renders/main/A7.webp",
    "J25": "/renders/main/J25.webp",
    "J43": "/renders/main/J43.webp",
    "J7": "/renders/main/J7.webp",
    "K25": "/renders/main/K25.webp",
    "K43": "/renders/main/K43.webp",
    "K7": "/renders/main/K7.webp",
    "R21": "/renders/main/R21.webp",
    "R37": "/renders/main/R37.webp",
    "R6": "/renders/main/R6.webp"
  }
};
